;;; gitmojis-list.el --- provide gitmojis list.  -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:

(defvar gitmojis-list '(("Improve structure / format of the code." ":art:" #x1F3A8)
                        ("Improve performance." ":zap:" #x26A1)
                        ("Remove code or files." ":fire:" #x1F525)
                        ("Fix a bug." ":bug:" #x1F41B)
                        ("Critical hotfix." ":ambulance:" #x1F691)
                        ("Introduce new features." ":sparkles:" #x2728)
                        ("Add or update documentation." ":memo:" #x1F4DD)
                        ("Deploy stuff." ":rocket:" #x1F680)
                        ("Add or update the UI and style files." ":lipstick:" #x1F484)
                        ("Begin a project." ":tada:" #x1F389)
                        ("Add, update, or pass tests." ":white_check_mark:" #x2705)
                        ("Fix security or privacy issues." ":lock:" #x1F512)
                        ("Add or update secrets." ":closed_lock_with_key:" #x1F510)
                        ("Release / Version tags." ":bookmark:" #x1F516)
                        ("Fix compiler / linter warnings." ":rotating_light:" #x1F6A8)
                        ("Work in progress." ":construction:" #x1F6A7)
                        ("Fix CI Build." ":green_heart:" #x1F49A)
                        ("Downgrade dependencies." ":arrow_down:" #x2B07)
                        ("Upgrade dependencies." ":arrow_up:" #x2B06)
                        ("Pin dependencies to specific versions." ":pushpin:" #x1F4CC)
                        ("Add or update CI build system." ":construction_worker:" #x1F477)
                        ("Add or update analytics or track code." ":chart_with_upwards_trend:" #x1F4C8)
                        ("Refactor code." ":recycle:" #x267B)
                        ("Add a dependency." ":heavy_plus_sign:" #x2795)
                        ("Remove a dependency." ":heavy_minus_sign:" #x2796)
                        ("Add or update configuration files." ":wrench:" #x1F527)
                        ("Add or update development scripts." ":hammer:" #x1F528)
                        ("Internationalization and localization." ":globe_with_meridians:" #x1F310)
                        ("Fix typos." ":pencil2:" #x270F)
                        ("Write bad code that needs to be improved." ":poop:" #x1F4A9)
                        ("Revert changes." ":rewind:" #x23EA)
                        ("Merge branches." ":twisted_rightwards_arrows:" #x1F500)
                        ("Add or update compiled files or packages." ":package:" #x1F4E6)
                        ("Update code due to external API changes." ":alien:" #x1F47D)
                        ("Move or rename resources (e.g.: files, paths, routes)." ":truck:" #x1F69A)
                        ("Add or update license." ":page_facing_up:" #x1F4C4)
                        ("Introduce breaking changes." ":boom:" #x1F4A5)
                        ("Add or update assets." ":bento:" #x1F371)
                        ("Improve accessibility." ":wheelchair:" #x267F)
                        ("Add or update comments in source code." ":bulb:" #x1F4A1)
                        ("Write code drunkenly." ":beers:" #x1F37B)
                        ("Add or update text and literals." ":speech_balloon:" #x1F4AC)
                        ("Perform database related changes." ":card_file_box:" #x1F5C3)
                        ("Add or update logs." ":loud_sound:" #x1F50A)
                        ("Remove logs." ":mute:" #x1F507)
                        ("Add or update contributor(s)." ":busts_in_silhouette:" #x1F465)
                        ("Improve user experience / usability." ":children_crossing:" #x1F6B8)
                        ("Make architectural changes." ":building_construction:" #x1F3D7)
                        ("Work on responsive design." ":iphone:" #x1F4F1)
                        ("Mock things." ":clown_face:" #x1F921)
                        ("Add or update an easter egg." ":egg:" #x1F95A)
                        ("Add or update a .gitignore file." ":see_no_evil:" #x1F648)
                        ("Add or update snapshots." ":camera_flash:" #x1F4F8)
                        ("Perform experiments." ":alembic:" #x2697)
                        ("Improve SEO." ":mag:" #x1F50D)
                        ("Add or update types." ":label:" #x1F3F7)
                        ("Add or update seed files." ":seedling:" #xFFFD)
                        ("Add, update, or remove feature flags." ":triangular_flag_on_post:" #x1F6A9)
                        ("Catch errors." ":goal_net:" #x1F945)
                        ("Add or update animations and transitions." ":dizzy:" #x1F4AB)
                        ("Deprecate code that needs to be cleaned up." ":wastebasket:" #x1F5D1)
                        ("Work on code related to authorization, roles and permissions." ":passport_control:" #x1F6C2)
                        ("Simple fix for a non-critical issue." ":adhesive_bandage:" #x1FA79)
                        ("Data exploration/inspection." ":monocle_face:" #x1F9D0)
                        ("Remove dead code." ":coffin:" #x26B0)
                        ("Add a failing test." ":test_tube:" #x1F9EA)
                        ("Add or update business logic." ":necktie:" #x1F454)
                        ("Add or update healthcheck." ":stethoscope:" #x1FA7A)
                        ("Infrastructure related changes." ":bricks:" #x1F9F1)
                        ("Improve developer experience." ":technologist:" #x1F9D1)
                        ("Add sponsorships or money related infrastructure." ":money_with_wings:" #x1F4B8)
                        ("Add or update code related to multithreading or concurrency." ":thread:" #x1F9F5)
                        ("Add or update code related to validation." ":safety_vest:" #x1F9BA)
                        ("Improve offline support." ":airplane:" #x2708)))
(provide 'gitmojis-list)
;;; gitmojis-list.el ends here.
